name: Build EXE with PyInstaller

on:
  push:
    branches: [main]  # Trigger on push to the main branch
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner to build the EXE

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller  # Install PyInstaller for building the .exe

      - name: Build EXE
        run: |
          pyinstaller --onefile your_script.py  # Replace 'your_script.py' with your script name

      - name: Upload EXE
        uses: actions/upload-artifact@v3  # Upload the built .exe as an artifact
        with:
          name: python-exe  # Artifact name
          path: dist/*.exe  # Path to the generated .exe file
