name: Build Windows EXE with PyInstaller

on:
  push:
    tags:
      - 'v*'  # Triggers only when pushing a version tag like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pyinstaller pywin32 keyboard
        pip install --upgrade --extra-index-url https://PySimpleGUI.net/install PySimpleGUI


    - name: Build EXE
      run: |
        pyinstaller --onefile --icon=item_frame.ico duper.py

    - name: Upload EXE to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/duper.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
